module.exports = {
  openapi: '3.0.1',
  info: {
    title: 'Sequence API',
    description: "Welcome to the Sequence API documentation.<br/><br/>Developed for the UOL Computer Science Agile Software Development module by <b>Team 61</b> (T6G6).",
    version: '0.0.1'
  },
  servers: [
    { url: 'https://yhw44o1elj.execute-api.eu-west-1.amazonaws.com/prod' }
  ],
  tags: [
    { name: 'Games', description: 'The /games endpoint is for main endpoint used for creating a new game, joining an existing game, playing a round and getting the game state.' },
  ],
  components: {
    securitySchemes: {
      bearerAuth: {
        description: '<br/><br/>We use Bearer authentication for requests to the Sequence API endpoints. The token is simply a UUID generated by the client. The UUID must remain the same between requests to uniquely identify the Player. In the Slate code samples, replace {access-token} with a valid UUID.',
        type: 'http',
        scheme: 'bearer'
      }
    }
  }
};
