#!/bin/bash

aws s3 --region eu-west-1 sync "/Users/callen/Documents/Personal/CompSci/CM2020 ASP/CM2020/client-web" s3://compsci/CM2020/client-web --exclude 'deploy' --exclude '.DS_Store' --acl public-read
